version: "3"
services:
  mysql:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: immelting
      MYSQL_USER: powerdns
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: powerdns
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
  powerdns:
    image: psitrax/powerdns
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: powerdns
      MYSQL_PASS: secret
      MYSQL_DB: powerdns
    networks:
      - backend
    volumes:
      - ./.docker/pdns:/etc/pdns/conf.d
    ports:
      - 8081:8081
volumes:
  database: {}
networks:
  backend: {}
